"""Data modifier

Revision ID: 03ff99d61cce
Revises: eed1c8a3b583
Create Date: 2024-12-16 21:39:50.243116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ff99d61cce'
down_revision = 'eed1c8a3b583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_index('owner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.create_index('owner', ['owner'], unique=True)

    # ### end Alembic commands ###
