"""Add bot

Revision ID: c2f824051920
Revises: 03ff99d61cce
Create Date: 2024-12-16 23:18:21.834884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2f824051920'
down_revision = '03ff99d61cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=2048),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###
